### ISSUE TITLE
Multiple Return Values

### ISSUE THREAD

**Issue by 1MLightyears** [odashi/latexify_py#18]
I'm submitting this issue, instead of directly working on it, because I'm not sure if multiple return values is practical or not.

Actually, I haven't seen any function in papers I read has more than one return value, but in some special occasions-say pseudo codes-I do see some functions "equal" a list of numbers, like `pseudo_linspace(n)=1,2,...,n-1`

Are we going to take these occasions in consideration, or abandon them, for they are literally rarely seen?

**Comment by odashi** [comment]
I think math formula is basically not designed for multiple return values, but sometimes they are represented as a tuple, i.e., direct product of some single values.

In Python, returning multiple values like `return a, b, c` is just the same as returning a tuple `return (a, b, c)` and it reasonably corresponds to the math formula. In this case, we need not to add any special treatment because both looks already the same.

Python also supports decomposition of lists (e.g., `x, y, z = [a, b, c]` works fine), but this form can not be reasonably represented by type annotations when the inner values have different types, except using `Union` or `Any`.
So we should assume that such functions are just functions returning *a list* of something, not multiple values.

**Comment by odashi** [comment]
For lists of the same type values, e.g., `int`, it is represented as `List[int]` by the type annotation. In this case it is also better to assume that the function is returning *a list*.

**Comment by 1MLightyears** [comment]
Yes I know it returns tuple but the latex output writes something like `<_ast.Tuple object at 0x********`(or `_ast.List`, depending on which type is transferred to the return statement).
Now, latexify works like this:
```python3
def func(a,b):
  return (a+b,a-b)

print(get_latex(func))
#\operatorname{func}(a, b)\triangleq <_ast.Tuple object at 0x000002B53785A388>
```
What I want is something like:
```python3
def func(a, b):
  return (a + b, a - b)

print(get_latex(func))
#\operatorname{func}(a, b)\triangleq \left( a + b\space,\space a - b\right)
```
I'm thinking of implementing the logic of this part.

**Comment by odashi** [comment]
The reason is our parser does not implement `visit_Tuple` currently so all tuple expressions are not parsed for now (and it is the same for list and dict). As I am stopping to push everything (#17) it is welcome if you add it. I think implementing tuple and list are straightforward.

**Comment by 1MLightyears** [comment]
That's right, I'm just looking for an agreement of opinion for this. It will be very embarrassing if I implement it, then other contributors think it useless. Good luck!
